CREATE TABLE lancamento (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   descricao VARCHAR(255) NOT NULL,
   data_vencimento date NOT NULL,
   data_pagamento date,
   valor DECIMAL NOT NULL,
   observacao VARCHAR(255),
   tipo VARCHAR(255) NOT NULL,
   categoria_id BIGINT,
   pessoa_id BIGINT,
   CONSTRAINT pk_lancamento PRIMARY KEY (id)
);

ALTER TABLE lancamento ADD CONSTRAINT FK_LANCAMENTO_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categoria (id);

ALTER TABLE lancamento ADD CONSTRAINT FK_LANCAMENTO_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);